// lib/app_localizations.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'settings_provider.dart';

// Map chứa tất cả text theo ngôn ngữ
const Map<String, Map<String, String>> localizedValues = {
  'vi': {
    'home_title': 'Trang chủ',
    'login': 'Đăng nhập',
    'logout': 'Đăng xuất',
    'review_feed': 'Bảng review',
    'settings': 'Cài đặt',
    'language': 'Ngôn ngữ',
    'dark_mode': 'Chế độ tối',
    'theme_color': 'Màu chủ đạo',
    'font_size': 'Cỡ chữ',
    'send': 'Gửi',
    'no_reviews': 'Chưa có review nào.',
    'no_comments': 'Chưa có bình luận nào.',
    'register': 'Đăng ký',
    'username': 'Tên người dùng',
    'enter_username': 'Nhập tên người dùng',
    'enter_email': 'Nhập email',
    'invalid_email': 'Email không hợp lệ',
    'enter_password': 'Nhập mật khẩu',
    'register_success': 'Đăng ký thành công!',
    'register_failed': 'Đăng ký thất bại, thử lại',
    'login_success': 'Đăng nhập thành công!',
    'login_failed': 'Đăng nhập thất bại',
    'description': 'Giới thiệu',
    'no_description': 'Chưa có mô tả',
    'reviews': 'Đánh giá',
    'add_review': 'Thêm Review',
    'average_rating': 'Đánh giá trung bình',
    'map_placeholder': 'Map sẽ hiển thị ở đây',
    'content_review': 'Nội dung review',
    'enter_content': 'Nhập nội dung',
    'send_review': 'Gửi Review',
    'account_info': 'Thông tin tài khoản',
    'change_avatar': 'Đổi avatar',
    'name': 'Tên',
    'save_changes': 'Lưu thay đổi',
    'update_success': 'Cập nhật thông tin thành công',
    'update_failed': 'Cập nhật thất bại',
    'upload_avatar_success': 'Upload avatar thành công',
    'upload_avatar_failed': 'Upload avatar thất bại',
    'my_reviews': 'Quản lý bài review',
    'favorites': 'Quán ăn đã yêu thích',
    'register_prompt': 'Chưa có tài khoản. Đăng kí ngay.',
    'login_prompt': 'Đã có tài khoản. Đăng nhập ngay.',
    'email': 'Email',
    'password': 'Mật khẩu',
    'write_comment': 'Thêm bình luận',
    'introduction': 'Giới thiệu',
    'review_content': 'Nội dung',
    'submit_review': 'Thêm bài review',
    "restaurant_category": "Quán ăn",
    "loading": "Đang tải...",
    "error": "Lỗi",
    "no_restaurants": "Không có quán ăn nào",
    "search_hint": "Tìm kiếm",
    "no_categories": "Không có danh mục nào",
    "category_title": "Danh mục",
    "add_review_with_restaurant": "Thêm review với nhà hàng",
    "restaurant_info": "Thông tin nhà hàng",
    "restaurant_name": "Tên nhà hàng",
    "restaurant_address": "Địa chỉ nhà hàng",
    "restaurant_description": "Mô tả nhà hàng",
    "add_restaurant": "Thêm nhà hàng",
    "restaurant_added_success": "Thêm nhà hàng thành công",
    "restaurant_added_error": "Thêm nhà hàng thất bại",
    "review_info": "Thông tin review",
    "add_review_error": "Thêm review thất bại",
    "enter_name": "Vui lòng nhập tên",
    "enter_address": "Vui lòng nhập địa chỉ",
    "please_add_restaurant_first": "Vui lòng thêm nhà hàng trước",
    "comment_failed": "Bình luận thất bại!",
    "existing_restaurants": "Nhà hàng đã tồn tại",
    "select_restaurant": "Chọn nhà hàng",
    "favorites_fav": "Lươt yêu thích",
    "top_rated_restaurants":"Top quán ăn nổi bật",
  },
  'en': {
    'home_title': 'Home',
    'login': 'Login',
    'logout': 'Logout',
    'review_feed': 'Review Feed',
    'settings': 'Settings',
    'language': 'Language',
    'dark_mode': 'Dark Mode',
    'theme_color': 'Theme Color',
    'font_size': 'Font Size',
    'send': 'Send',
    'no_reviews': 'No reviews yet.',
    'no_comments': 'No comments yet.',
    'register': 'Register',
    'username': 'Username',
    'enter_username': 'Enter username',
    'enter_email': 'Enter email',
    'invalid_email': 'Invalid email',
    'enter_password': 'Enter password',
    'register_success': 'Registration successful!',
    'register_failed': 'Registration failed, try again',
    'login_success': 'Login successful!',
    'login_failed': 'Login failed',
    'description': 'Description',
    'no_description': 'No description available',
    'reviews': 'Reviews',
    'add_review': 'Add Review',
    'average_rating': 'Average rating',
    'map_placeholder': 'Map will be shown here',
    'content_review': 'Review Content',
    'enter_content': 'Enter content',
    'send_review': 'Send Review',
    'account_info': 'Account Info',
    'change_avatar': 'Change Avatar',
    'name': 'Name',
    'save_changes': 'Save Changes',
    'update_success': 'User info updated successfully',
    'update_failed': 'Update failed',
    'upload_avatar_success': 'Avatar uploaded successfully',
    'upload_avatar_failed': 'Avatar upload failed',
    'my_reviews': 'My Reviews',
    'favorites': 'Favorite Restaurants',
    'login_prompt': 'Already have an account? Log in now.',
    'register_prompt': 'No account yet. Sign up now.',
    'email': 'Email',
    'password': 'Password',
    'write_comment': 'Add comment',
    'introduction': 'Introduction',
    'review_content': 'Review content',
    'submit_review': 'Add review',
    "restaurant_category": "Quán ăn",
    "loading": "Đang tải...",
    "error": "Lỗi",
    "no_restaurants": "Không có quán ăn nào",
    "search_hint": "search",
    "no_categories": "No categories available",
    "category_title": "Categories",
    "add_review_with_restaurant": "Add review with restaurant",
    "restaurant_info": "Restaurant information",
    "restaurant_name": "Restaurant name",
    "restaurant_address": "Restaurant address",
    "restaurant_description": "Restaurant description",
    "add_restaurant": "Add restaurant",
    "restaurant_added_success": "Restaurant added successfully",
    "restaurant_added_error": "Failed to add restaurant",
    "review_info": "Review information",
    "add_review_error": "Failed to add review",
    "enter_name": "Please enter the name",
    "enter_address": "Please enter the address",
    "please_add_restaurant_first": "Please add a restaurant first",
    "comment_failed": "Fail to add comment!",
    "existing_restaurants": "Existing restaurants",
    "select_restaurant": "Select restaurant",
    "favorites_fav": "favorited",
    "top_rated_restaurants":"Top quán ăn nổi bật",
  },
};

// Extension trên BuildContext để lấy text theo key
extension Translate on BuildContext {
  /// Lấy text và rebuild khi SettingsProvider.language thay đổi
  String t(String key) {
    final lang = watch<SettingsProvider>().language;
    return localizedValues[lang]?[key] ?? key;
  }

  /// Lấy text nhưng KHÔNG rebuild (dùng trong onPressed, async...)
  String tRead(String key) {
    final lang = read<SettingsProvider>().language;
    return localizedValues[lang]?[key] ?? key;
  }
}
